This homework assignment will build three models on the advertising data and evaluate their performance. You can use tools from sklearn to complete this task.

Source of data:  https://www.statlearning.com/s/Advertising.csv

1. Use train_test_split to split the data into training set (80%) and test set (20%).

2. Build a multilinear regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_lr. Train the model on the training set and obtain model predictions on the test set.

3.  Build a degree 2 polynomial regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_pr2. Train the model on the training set and obtain model predictions on the test set.

4.  Build a degree 4 polynomial regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_pr4. Train the model on the training set and obtain model predictions on the test set.

5. Calculate the test MSE of each model using the mean_squared_error function. Which model gives the best MSE?

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
url = "https://www.statlearning.com/s/Advertising.csv"
df = pd.read_csv(url)
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [6]:
from sklearn.linear_model import LinearRegression

model_lr = LinearRegression()

model_lr.fit(df[["TV", "radio", "newspaper"]], df[["sales"]]) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:

# Retrieve the estimated parameter values.
print("Theta 0:", model_lr.intercept_)
print("Theta 1 and Theta 2:", model_lr.coef_)

Theta 0: [2.93888937]
Theta 1 and Theta 2: [[ 0.04576465  0.18853002 -0.00103749]]


In [8]:
# Remember prediction = theta0 + theta1 * tv + theta2 * radio + theta3 * newspaper
theta0 = 2.93888937
theta1 = 0.04576465
theta2 = 0.18853002
theta3 = -0.00103749

prediction_lr2 = theta0 + theta1 * 230.1 + theta2 * 37.8 + theta3 + 69.2
print(prediction_lr2)

89.79473260099999


In [9]:
theta = np.array([2.93888937, 0.04576465, 0.18853002,-0.00103749 ])

list_errors = []

for i in df.index:
    # print(i)
    x = np.array([1, df.loc[i, "TV"], df.loc[i, "radio"], df.loc[i, "newspaper"]])
    theta_dot_x = theta.dot(x)
    y = df.loc[i, "sales"]
    squared_error = (theta_dot_x - y) ** 2
    list_errors.append(squared_error)

print(list_errors)
print("MSE:", np.mean(list_errors))

[2.4838523325704758, 3.7552830939752964, 9.046086113478205, 0.8139097959042205, 0.08333203742095156, 27.860958168608885, 0.004933603374869262, 1.1600284997016992, 1.1505975190689908, 3.8058145675968853, 2.4576845661079663, 0.013195060613760221, 1.896462664531567, 0.7633499967703377, 0.31994006509921036, 2.4986102359223024, 0.10475418507402931, 1.3807219862032158, 1.8179600996826975, 0.18829200432470147, 0.010154294219916095, 5.020016655076762, 0.7905887254615187, 1.0939780683274185, 2.413302440620558, 13.032387862989614, 0.00010993382001450475, 1.3263544948459203, 0.26065038807635343, 1.8386698603387743, 0.05472574938323446, 0.30681231214690075, 3.8459772205703437, 2.144085353128217, 3.7062757671187763, 17.697397968129724, 3.976427308199339, 0.852812392205697, 0.0366027990532167, 1.1075212518443787, 0.049432515610382526, 0.038409816448849284, 0.8024660282931173, 1.1317936037321032, 0.15045111316439902, 0.0683948548808095, 2.981191484865793, 2.1826186598555575, 2.1421876464465983, 2.346

In [10]:
X = np.hstack([np.ones([200, 1]), df[["TV", "radio", "newspaper"]].values])
print(X)

[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]
 [  1.    8.7  48.9  75. ]
 [  1.   57.5  32.8  23.5]
 [  1.  120.2  19.6  11.6]
 [  1.    8.6   2.1   1. ]
 [  1.  199.8   2.6  21.2]
 [  1.   66.1   5.8  24.2]
 [  1.  214.7  24.    4. ]
 [  1.   23.8  35.1  65.9]
 [  1.   97.5   7.6   7.2]
 [  1.  204.1  32.9  46. ]
 [  1.  195.4  47.7  52.9]
 [  1.   67.8  36.6 114. ]
 [  1.  281.4  39.6  55.8]
 [  1.   69.2  20.5  18.3]
 [  1.  147.3  23.9  19.1]
 [  1.  218.4  27.7  53.4]
 [  1.  237.4   5.1  23.5]
 [  1.   13.2  15.9  49.6]
 [  1.  228.3  16.9  26.2]
 [  1.   62.3  12.6  18.3]
 [  1.  262.9   3.5  19.5]
 [  1.  142.9  29.3  12.6]
 [  1.  240.1  16.7  22.9]
 [  1.  248.8  27.1  22.9]
 [  1.   70.6  16.   40.8]
 [  1.  292.9  28.3  43.2]
 [  1.  112.9  17.4  38.6]
 [  1.   97.2   1.5  30. ]
 [  1.  265.6  20.    0.3]
 [  1.   95.7   1.4   7.4]
 [  1.  290.7   4.1   8.5]
 [  1.  266.9  43.8   5. ]
 

In [12]:
y = df[["sales"]].values
print(y)

[[22.1]
 [10.4]
 [ 9.3]
 [18.5]
 [12.9]
 [ 7.2]
 [11.8]
 [13.2]
 [ 4.8]
 [10.6]
 [ 8.6]
 [17.4]
 [ 9.2]
 [ 9.7]
 [19. ]
 [22.4]
 [12.5]
 [24.4]
 [11.3]
 [14.6]
 [18. ]
 [12.5]
 [ 5.6]
 [15.5]
 [ 9.7]
 [12. ]
 [15. ]
 [15.9]
 [18.9]
 [10.5]
 [21.4]
 [11.9]
 [ 9.6]
 [17.4]
 [ 9.5]
 [12.8]
 [25.4]
 [14.7]
 [10.1]
 [21.5]
 [16.6]
 [17.1]
 [20.7]
 [12.9]
 [ 8.5]
 [14.9]
 [10.6]
 [23.2]
 [14.8]
 [ 9.7]
 [11.4]
 [10.7]
 [22.6]
 [21.2]
 [20.2]
 [23.7]
 [ 5.5]
 [13.2]
 [23.8]
 [18.4]
 [ 8.1]
 [24.2]
 [15.7]
 [14. ]
 [18. ]
 [ 9.3]
 [ 9.5]
 [13.4]
 [18.9]
 [22.3]
 [18.3]
 [12.4]
 [ 8.8]
 [11. ]
 [17. ]
 [ 8.7]
 [ 6.9]
 [14.2]
 [ 5.3]
 [11. ]
 [11.8]
 [12.3]
 [11.3]
 [13.6]
 [21.7]
 [15.2]
 [12. ]
 [16. ]
 [12.9]
 [16.7]
 [11.2]
 [ 7.3]
 [19.4]
 [22.2]
 [11.5]
 [16.9]
 [11.7]
 [15.5]
 [25.4]
 [17.2]
 [11.7]
 [23.8]
 [14.8]
 [14.7]
 [20.7]
 [19.2]
 [ 7.2]
 [ 8.7]
 [ 5.3]
 [19.8]
 [13.4]
 [21.8]
 [14.1]
 [15.9]
 [14.6]
 [12.6]
 [12.2]
 [ 9.4]
 [15.9]
 [ 6.6]
 [15.5]
 [ 7. ]
 [11.6]
 [15.2]
 [19.7]


In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model_lr2 = LinearRegression()
model_lr2.fit(X, y)
predictions_lr2 = model_lr2.predict(X)
MSE_lr2 = mean_squared_error(y, predictions_lr2)
print("MSE of the linear regression model:", MSE_lr2)

MSE of the linear regression model: 2.784126314510936


In [14]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False)
poly_features.fit(X)
X_poly = poly_features.transform(X)

print(X_poly[:5])

[[1.000000e+00 2.301000e+02 3.780000e+01 6.920000e+01 1.000000e+00
  2.301000e+02 3.780000e+01 6.920000e+01 5.294601e+04 8.697780e+03
  1.592292e+04 1.428840e+03 2.615760e+03 4.788640e+03]
 [1.000000e+00 4.450000e+01 3.930000e+01 4.510000e+01 1.000000e+00
  4.450000e+01 3.930000e+01 4.510000e+01 1.980250e+03 1.748850e+03
  2.006950e+03 1.544490e+03 1.772430e+03 2.034010e+03]
 [1.000000e+00 1.720000e+01 4.590000e+01 6.930000e+01 1.000000e+00
  1.720000e+01 4.590000e+01 6.930000e+01 2.958400e+02 7.894800e+02
  1.191960e+03 2.106810e+03 3.180870e+03 4.802490e+03]
 [1.000000e+00 1.515000e+02 4.130000e+01 5.850000e+01 1.000000e+00
  1.515000e+02 4.130000e+01 5.850000e+01 2.295225e+04 6.256950e+03
  8.862750e+03 1.705690e+03 2.416050e+03 3.422250e+03]
 [1.000000e+00 1.808000e+02 1.080000e+01 5.840000e+01 1.000000e+00
  1.808000e+02 1.080000e+01 5.840000e+01 3.268864e+04 1.952640e+03
  1.055872e+04 1.166400e+02 6.307200e+02 3.410560e+03]]


In [16]:
from sklearn.linear_model import LinearRegression
model_pr2 = LinearRegression()
model_pr2.fit(X_poly, y)
print(model_pr2.coef_, model_pr2.intercept_)

[[ 0.00000000e+00  2.58262743e-02  1.05371485e-02  3.44186766e-03
  -2.60208521e-18  2.58262743e-02  1.05371485e-02  3.44186766e-03
  -1.09702663e-04  1.10525949e-03 -4.55155391e-05  1.11997015e-04
   8.26605896e-05  1.19125650e-05]] [5.08478167]


In [17]:
url2 = "https://www.statlearning.com/s/Advertising.csv"
df2 = pd.read_csv(url2)
df2

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [18]:
from sklearn.linear_model import LinearRegression

model_lr4 = LinearRegression()

model_lr4.fit(df2[["TV", "radio", "newspaper"]], df2[["sales"]]) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
print("Theta 0:", model_lr4.intercept_)
print("Theta 1 and Theta 2:", model_lr4.coef_)

Theta 0: [2.93888937]
Theta 1 and Theta 2: [[ 0.04576465  0.18853002 -0.00103749]]


In [20]:
# Remember prediction = theta0 + theta1 * tv + theta2 * radio + theta3 * newspaper
theta0 = 2.93888937
theta1 = 0.04576465
theta2 = 0.18853002
theta3 = -0.00103749

prediction_lr4 = theta0 + theta1 * 230.1 + theta2 * 37.8 + theta3 + 69.2
print(prediction_lr4)

89.79473260099999


In [22]:
theta = np.array([2.93888937, 0.04576465, 0.18853002,-0.00103749 ])

list_errors = []

for i in df.index:
    # print(i)
    x = np.array([1, df2.loc[i, "TV"], df2.loc[i, "radio"], df2.loc[i, "newspaper"]])
    theta_dot_x = theta.dot(x)
    y = df2.loc[i, "sales"]
    squared_error = (theta_dot_x - y) ** 2
    list_errors.append(squared_error)

print(list_errors)
print("MSE:", np.mean(list_errors))

[2.4838523325704758, 3.7552830939752964, 9.046086113478205, 0.8139097959042205, 0.08333203742095156, 27.860958168608885, 0.004933603374869262, 1.1600284997016992, 1.1505975190689908, 3.8058145675968853, 2.4576845661079663, 0.013195060613760221, 1.896462664531567, 0.7633499967703377, 0.31994006509921036, 2.4986102359223024, 0.10475418507402931, 1.3807219862032158, 1.8179600996826975, 0.18829200432470147, 0.010154294219916095, 5.020016655076762, 0.7905887254615187, 1.0939780683274185, 2.413302440620558, 13.032387862989614, 0.00010993382001450475, 1.3263544948459203, 0.26065038807635343, 1.8386698603387743, 0.05472574938323446, 0.30681231214690075, 3.8459772205703437, 2.144085353128217, 3.7062757671187763, 17.697397968129724, 3.976427308199339, 0.852812392205697, 0.0366027990532167, 1.1075212518443787, 0.049432515610382526, 0.038409816448849284, 0.8024660282931173, 1.1317936037321032, 0.15045111316439902, 0.0683948548808095, 2.981191484865793, 2.1826186598555575, 2.1421876464465983, 2.346

In [23]:
X = np.hstack([np.ones([200, 1]), df2[["TV", "radio", "newspaper"]].values])
print(X)

[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]
 [  1.    8.7  48.9  75. ]
 [  1.   57.5  32.8  23.5]
 [  1.  120.2  19.6  11.6]
 [  1.    8.6   2.1   1. ]
 [  1.  199.8   2.6  21.2]
 [  1.   66.1   5.8  24.2]
 [  1.  214.7  24.    4. ]
 [  1.   23.8  35.1  65.9]
 [  1.   97.5   7.6   7.2]
 [  1.  204.1  32.9  46. ]
 [  1.  195.4  47.7  52.9]
 [  1.   67.8  36.6 114. ]
 [  1.  281.4  39.6  55.8]
 [  1.   69.2  20.5  18.3]
 [  1.  147.3  23.9  19.1]
 [  1.  218.4  27.7  53.4]
 [  1.  237.4   5.1  23.5]
 [  1.   13.2  15.9  49.6]
 [  1.  228.3  16.9  26.2]
 [  1.   62.3  12.6  18.3]
 [  1.  262.9   3.5  19.5]
 [  1.  142.9  29.3  12.6]
 [  1.  240.1  16.7  22.9]
 [  1.  248.8  27.1  22.9]
 [  1.   70.6  16.   40.8]
 [  1.  292.9  28.3  43.2]
 [  1.  112.9  17.4  38.6]
 [  1.   97.2   1.5  30. ]
 [  1.  265.6  20.    0.3]
 [  1.   95.7   1.4   7.4]
 [  1.  290.7   4.1   8.5]
 [  1.  266.9  43.8   5. ]
 

In [24]:
y = df2[["sales"]].values
print(y)

[[22.1]
 [10.4]
 [ 9.3]
 [18.5]
 [12.9]
 [ 7.2]
 [11.8]
 [13.2]
 [ 4.8]
 [10.6]
 [ 8.6]
 [17.4]
 [ 9.2]
 [ 9.7]
 [19. ]
 [22.4]
 [12.5]
 [24.4]
 [11.3]
 [14.6]
 [18. ]
 [12.5]
 [ 5.6]
 [15.5]
 [ 9.7]
 [12. ]
 [15. ]
 [15.9]
 [18.9]
 [10.5]
 [21.4]
 [11.9]
 [ 9.6]
 [17.4]
 [ 9.5]
 [12.8]
 [25.4]
 [14.7]
 [10.1]
 [21.5]
 [16.6]
 [17.1]
 [20.7]
 [12.9]
 [ 8.5]
 [14.9]
 [10.6]
 [23.2]
 [14.8]
 [ 9.7]
 [11.4]
 [10.7]
 [22.6]
 [21.2]
 [20.2]
 [23.7]
 [ 5.5]
 [13.2]
 [23.8]
 [18.4]
 [ 8.1]
 [24.2]
 [15.7]
 [14. ]
 [18. ]
 [ 9.3]
 [ 9.5]
 [13.4]
 [18.9]
 [22.3]
 [18.3]
 [12.4]
 [ 8.8]
 [11. ]
 [17. ]
 [ 8.7]
 [ 6.9]
 [14.2]
 [ 5.3]
 [11. ]
 [11.8]
 [12.3]
 [11.3]
 [13.6]
 [21.7]
 [15.2]
 [12. ]
 [16. ]
 [12.9]
 [16.7]
 [11.2]
 [ 7.3]
 [19.4]
 [22.2]
 [11.5]
 [16.9]
 [11.7]
 [15.5]
 [25.4]
 [17.2]
 [11.7]
 [23.8]
 [14.8]
 [14.7]
 [20.7]
 [19.2]
 [ 7.2]
 [ 8.7]
 [ 5.3]
 [19.8]
 [13.4]
 [21.8]
 [14.1]
 [15.9]
 [14.6]
 [12.6]
 [12.2]
 [ 9.4]
 [15.9]
 [ 6.6]
 [15.5]
 [ 7. ]
 [11.6]
 [15.2]
 [19.7]


In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model_lr4 = LinearRegression()
model_lr4.fit(X, y)
predictions_lr4 = model_lr4.predict(X)
MSE_lr4 = mean_squared_error(y, predictions_lr4)
print("MSE of the linear regression model:", MSE_lr4)

MSE of the linear regression model: 2.784126314510936


In [28]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=10, include_bias=False)
poly_features.fit(X)
X_poly = poly_features.transform(X)

print(X_poly[:5])

[[1.00000000e+00 2.30100000e+02 3.78000000e+01 ... 7.51332811e+17
  1.37545583e+18 2.51803026e+18]
 [1.00000000e+00 4.45000000e+01 3.93000000e+01 ... 2.64361030e+16
  3.03376144e+16 3.48149214e+16]
 [1.00000000e+00 1.72000000e+01 4.59000000e+01 ... 1.12070484e+18
  1.69204456e+18 2.55465552e+18]
 [1.00000000e+00 1.51500000e+02 4.13000000e+01 ... 2.33962919e+17
  3.31400261e+17 4.69416835e+17]
 [1.00000000e+00 1.80800000e+02 1.08000000e+01 ... 1.57815730e+16
  8.53373946e+16 4.61454060e+17]]


In [29]:
from sklearn.linear_model import LinearRegression
model_pr4 = LinearRegression()
model_pr4.fit(X_poly, y)
print(model_pr4.coef_, model_pr4.intercept_)

[[-1.49492261e-12  9.08764548e-11  1.30384664e-14  1.32399001e-12
  -1.81173695e-12 -7.44830004e-15  2.00688187e-13  3.33406646e-13
  -3.93640096e-13 -7.50198564e-14  1.27886750e-13  2.83804057e-15
   1.48358588e-14 -1.48249855e-13  2.86303772e-14  1.20057269e-13
  -2.48137386e-16 -2.54172351e-15  3.25094306e-15  1.76943678e-17
  -5.26643443e-16 -1.33892864e-15  2.08049678e-16  1.48237058e-16
   4.37240789e-14  5.24310676e-15  4.95846702e-15  6.04765325e-16
   8.76301074e-16  1.09368883e-15 -4.02596663e-16  9.04359208e-17
   3.70647184e-17 -2.60927111e-16  4.27992003e-17 -7.78150590e-17
  -1.12045557e-17  1.22350141e-17  7.08412264e-16  8.09371216e-17
   1.06026281e-16 -3.14315377e-18 -6.21924821e-18 -1.57794077e-17
   4.36250418e-14  4.91017333e-15  5.26784388e-15  8.79477024e-16
   7.49753209e-16  1.36715209e-15  3.44702744e-17 -5.37242528e-17
  -4.63533046e-17 -2.70272939e-16  2.07971675e-12  2.33558018e-13
   2.59941238e-13  5.50968545e-14  4.98688339e-14  1.17573168e-13
   1.33268